// src/components/site-header.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { Menu, Phone, X } from "lucide-react";
import { agency } from "@/lib/listings";
import { cn } from "@/lib/utils";

const links = [
  { href: "/propiedades", label: "Propiedades" },
  { href: "/nosotros", label: "Nosotros" },
  { href: "/tasaciones", label: "Tasaciones" },
  { href: "/contacto", label: "Contacto" },
];

export function SiteHeader() {
  const pathname = usePathname();
  const [open, setOpen] = useState(false);

  return (
    <header className="sticky top-0 z-50 border-b border-line/70 bg-mist/80 backdrop-blur-md">
      <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-3 md:px-6">
        <Link href="/" className="group min-w-0" onClick={() => setOpen(false)}>
          <p className="font-display text-xl leading-none tracking-tight text-forest-deep md:text-2xl">
            Sierra de la Ventana
          </p>
          <p className="mt-1 text-[11px] uppercase tracking-[0.18em] text-ink-soft">
            Inmobiliaria
          </p>
        </Link>

        <nav className="hidden items-center gap-1 md:flex">
          {links.map((link) => (
            <Link
              key={link.href}
              href={link.href}
              className={cn(
                "rounded-md px-3 py-2 text-sm transition",
                pathname.startsWith(link.href)
                  ? "bg-forest/10 text-forest-deep"
                  : "text-ink-soft hover:bg-mist hover:text-ink",
              )}
            >
              {link.label}
            </Link>
          ))}
        </nav>

        <div className="flex items-center gap-2">
          <a
            href={agency.phoneHref}
            className="hidden items-center gap-2 rounded-md border border-line bg-mist/80 px-3 py-2 text-sm text-forest-deep transition hover:bg-white sm:inline-flex"
          >
            <Phone className="size-4" />
            {agency.phone}
          </a>
          <button
            type="button"
            className="inline-flex size-10 items-center justify-center rounded-md border border-line bg-mist/80 md:hidden"
            aria-label={open ? "Cerrar menú" : "Abrir menú"}
            onClick={() => setOpen((v) => !v)}
          >
            {open ? <X className="size-5" /> : <Menu className="size-5" />}
          </button>
        </div>
      </div>

      {open ? (
        <div className="border-t border-line bg-mist px-4 py-3 md:hidden">
          <nav className="flex flex-col gap-1">
            {links.map((link) => (
              <Link
                key={link.href}
                href={link.href}
                onClick={() => setOpen(false)}
                className={cn(
                  "rounded-md px-3 py-3 text-base",
                  pathname.startsWith(link.href)
                    ? "bg-forest/10 text-forest-deep"
                    : "text-ink-soft",
                )}
              >
                {link.label}
              </Link>
            ))}
            <a
              href={agency.phoneHref}
              className="mt-2 inline-flex items-center gap-2 rounded-md bg-forest px-3 py-3 text-mist"
            >
              <Phone className="size-4" />
              Llamar {agency.phone}
            </a>
          </nav>
        </div>
      ) : null}
    </header>
  );
}

// src/app/shared/site-header.component.ts
import { Component, signal } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { agency } from '../core/listings';

@Component({
  selector: 'app-site-header',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  template: `
    <header class="header">
      <div class="bar">
        <a routerLink="/" class="brand" (click)="menuOpen.set(false)">
          <span class="name">Sierra de la Ventana</span>
          <span class="sub">Inmobiliaria</span>
        </a>

        <nav class="nav desktop">
          @for (link of links; track link.path) {
            <a
              [routerLink]="link.path"
              routerLinkActive="active"
              [routerLinkActiveOptions]="{ exact: false }"
              >{{ link.label }}</a
            >
          }
        </nav>

        <div class="actions">
          <a class="phone" [href]="agency.phoneHref">{{ agency.phone }}</a>
          <button
            type="button"
            class="burger"
            (click)="toggleMenu()"
            [attr.aria-expanded]="menuOpen()"
            aria-label="Menú"
          >
            {{ menuOpen() ? '✕' : '☰' }}
          </button>
        </div>
      </div>

      @if (menuOpen()) {
        <div class="mobile">
          @for (link of links; track link.path) {
            <a [routerLink]="link.path" (click)="menuOpen.set(false)">{{
              link.label
            }}</a>
          }
          <a [href]="agency.whatsapp" target="_blank" rel="noreferrer"
            >WhatsApp</a
          >
        </div>
      }
    </header>
  `,
  styles: [
    `
      .header {
        position: sticky;
        top: 0;
        z-index: 40;
        border-bottom: 1px solid var(--line);
        background: color-mix(in srgb, var(--mist) 90%, transparent);
        backdrop-filter: blur(14px);
      }
      .bar {
        max-width: 72rem;
        margin: 0 auto;
        padding: 0.85rem 1.25rem;
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 1rem;
      }
      .brand {
        text-decoration: none;
        color: var(--forest-deep);
      }
      .name {
        display: block;
        font-family: var(--font-display);
        font-size: 1.35rem;
        line-height: 1;
      }
      .sub {
        display: block;
        margin-top: 0.3rem;
        font-size: 0.68rem;
        letter-spacing: 0.18em;
        text-transform: uppercase;
        color: var(--ink-soft);
      }
      .nav {
        display: none;
        gap: 0.2rem;
      }
      .nav a {
        text-decoration: none;
        color: var(--ink-soft);
        font-weight: 600;
        font-size: 0.92rem;
        padding: 0.5rem 0.85rem;
        border-radius: 0.5rem;
      }
      .nav a.active,
      .nav a:hover {
        background: var(--forest);
        color: #fff;
      }
      .actions {
        display: flex;
        align-items: center;
        gap: 0.5rem;
      }
      .phone {
        display: none;
        text-decoration: none;
        background: var(--forest-deep);
        color: #fff;
        font-weight: 600;
        font-size: 0.85rem;
        padding: 0.55rem 0.9rem;
        border-radius: 0.55rem;
      }
      .burger {
        width: 2.5rem;
        height: 2.5rem;
        border: 2px solid var(--forest);
        border-radius: 0.5rem;
        background: #fff;
        color: var(--forest);
        cursor: pointer;
      }
      .mobile {
        display: grid;
        gap: 0.2rem;
        padding: 0.75rem 1.25rem 1rem;
        border-top: 1px solid var(--line);
        background: #fff;
      }
      .mobile a {
        text-decoration: none;
        color: var(--ink);
        font-weight: 600;
        padding: 0.75rem 0.85rem;
        border-radius: 0.5rem;
      }
      @media (min-width: 768px) {
        .nav {
          display: flex;
        }
        .phone {
          display: inline-flex;
        }
        .burger,
        .mobile {
          display: none;
        }
      }
    `,
  ],
})
export class SiteHeaderComponent {
  readonly agency = agency;
  readonly menuOpen = signal(false);
  readonly links = [
    { path: '/propiedades', label: 'Propiedades' },
    { path: '/nosotros', label: 'Nosotros' },
    { path: '/tasaciones', label: 'Tasaciones' },
    { path: '/contacto', label: 'Contacto' },
  ];

  toggleMenu() {
    this.menuOpen.update((v) => !v);
  }
}
