// src/app/shared/site-footer.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { agency } from '../core/listings';

@Component({
  selector: 'app-site-footer',
  standalone: true,
  imports: [RouterLink],
  template: `
    <footer class="footer">
      <div class="grid">
        <div>
          <p class="name">{{ agency.name }}</p>
          <p class="tag">{{ agency.tagline }}</p>
        </div>
        <div>
          <p class="label">Contacto</p>
          <a [href]="agency.phoneHref">{{ agency.phone }}</a>
          <a [href]="'mailto:' + agency.email">{{ agency.email }}</a>
          <a [href]="agency.whatsapp" target="_blank" rel="noreferrer"
            >WhatsApp</a
          >
        </div>
        <div>
          <p class="label">Explorar</p>
          <a routerLink="/propiedades">Propiedades</a>
          <a routerLink="/tasaciones">Tasaciones</a>
          <a routerLink="/contacto">Contacto</a>
        </div>
      </div>
      <p class="copy">{{ agency.address }} · {{ agency.hours }}</p>
    </footer>
  `,
  styles: [
    `
      .footer {
        margin-top: auto;
        background: var(--forest-deep);
        color: rgba(255, 255, 255, 0.82);
        padding: 3rem 1.25rem 2rem;
      }
      .grid {
        max-width: 72rem;
        margin: 0 auto;
        display: grid;
        gap: 2rem;
      }
      .name {
        margin: 0;
        font-family: var(--font-display);
        font-size: 1.6rem;
        color: #fff;
      }
      .tag {
        margin: 0.6rem 0 0;
        max-width: 28rem;
        line-height: 1.5;
      }
      .label {
        margin: 0 0 0.55rem;
        font-size: 0.72rem;
        letter-spacing: 0.18em;
        text-transform: uppercase;
        color: var(--sand);
      }
      a {
        display: block;
        margin-top: 0.35rem;
        color: rgba(255, 255, 255, 0.85);
        text-decoration: none;
      }
      a:hover {
        color: #fff;
      }
      .copy {
        max-width: 72rem;
        margin: 2rem auto 0;
        padding-top: 1.2rem;
        border-top: 1px solid rgba(255, 255, 255, 0.15);
        font-size: 0.85rem;
        color: rgba(255, 255, 255, 0.55);
      }
      @media (min-width: 768px) {
        .grid {
          grid-template-columns: 1.4fr 1fr 1fr;
        }
      }
    `,
  ],
})
export class SiteFooterComponent {
  readonly agency = agency;
}

// src/components/site-footer.tsx
import Link from "next/link";
import { Mail, MapPin, Phone } from "lucide-react";
import { agency } from "@/lib/listings";

export function SiteFooter() {
  return (
    <footer className="mt-auto border-t border-line bg-forest-deep text-mist">
      <div className="mx-auto grid max-w-6xl gap-10 px-4 py-14 md:grid-cols-[1.4fr_1fr_1fr] md:px-6">
        <div>
          <p className="font-display text-3xl tracking-tight">
            Inmobiliaria Sierra de la Ventana
          </p>
          <p className="mt-3 max-w-md text-sm leading-relaxed text-mist/80">
            Te acompañamos a encontrar tu hogar, tu refugio o tu próxima
            inversión en un entorno único. Compromiso, transparencia y atención
            cercana.
          </p>
        </div>

        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-sand">Explorar</p>
          <ul className="mt-4 space-y-2 text-sm text-mist/85">
            <li>
              <Link href="/propiedades" className="hover:text-white">
                Propiedades
              </Link>
            </li>
            <li>
              <Link href="/tasaciones" className="hover:text-white">
                Pedir tasación
              </Link>
            </li>
            <li>
              <Link href="/nosotros" className="hover:text-white">
                Nosotros
              </Link>
            </li>
            <li>
              <Link href="/contacto" className="hover:text-white">
                Contacto
              </Link>
            </li>
          </ul>
        </div>

        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-sand">Contacto</p>
          <ul className="mt-4 space-y-3 text-sm text-mist/85">
            <li className="flex items-start gap-2">
              <MapPin className="mt-0.5 size-4 shrink-0" />
              {agency.address}
            </li>
            <li className="flex items-center gap-2">
              <Phone className="size-4 shrink-0" />
              <a href={agency.phoneHref} className="hover:text-white">
                {agency.phone}
              </a>
            </li>
            <li className="flex items-center gap-2">
              <Mail className="size-4 shrink-0" />
              <a href={`mailto:${agency.email}`} className="hover:text-white">
                {agency.email}
              </a>
            </li>
            <li className="text-mist/70">{agency.hours}</li>
          </ul>
        </div>
      </div>
      <div className="border-t border-white/10 px-4 py-4 text-center text-xs text-mist/60 md:px-6">
        Rediseño demo con información pública de {agency.name}. No es el sitio
        oficial.
      </div>
    </footer>
  );
}
